contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bamcmp channel"
    url: https://nfcore.slack.com/channels/bamcmp
    about: Discussion about the nf-core/bamcmp pipeline
